apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jupyterhub-cost-monitoring.fullname" . }}
  labels: {{- include "jupyterhub-cost-monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.prometheusAuth.username | b64enc }}
  password: {{ .Values.prometheusAuth.password | b64enc }}